//BASEADO NO CODIGO ANTERIOR (LISTA DE INTEGER), CONSTRUIR UM PROGRAMA EM JAVA QUE RECEBA, VIA TECLADO DO USUARIO, N NOMES DE PESSOAS. ASSIM COMO O PRIMEIRO CODIGO:
//1)NÃO PODE HAVER NOMES DUPLICADOS 
//2) AO FINAL DO CADASTRO, A LISTA PRECISARÁ SER ORDENADA 
//3) O CODIGO DEVE PERMITIR QUE O USUARIO DIGITE UM NOME PARA PESQUISA E O PROGRAMA EXCLUA ESSE NOME DA LISTA
//4) EXIBIR NOVAMENTE A LISTA 
//-EM JAVA,COMO COLOCAR MAISCULO UM NOME ANTES DE ARMAZENA-LO NA LISTA.
